import { useState } from 'react'
import './App.css'

const App = () => {
  const [index, setIndex] = useState(0);
  const [currentCard, setCurrent] = useState(["to know", ["认识", "rèn shi"]]);
  const [currentLevel, setLevel] = useState(0);
  const [currentSide, setSide] = useState(0);

  const data = [
    {
    "to love": ["爱", "ài"],
    "eight": ["八", "bā"],
    "(informal) father": ["爸爸", "bà ba"],
    "cup": ["杯子", "bēi zi"],
    "Beijing": ["北京", "Běi jīng"],
    "roots or stems of plants": ["本", "běn"],
    "you're welcome": ["不客气", "bù kè qi"],
    "(negative prefix)": ["不", "bù"],
    "dish (type of food)": ["菜", "cài"],
    "tea": ["茶", "chá"],
    "to eat": ["吃", "chī"],
    "taxi": ["出租车", "chū zū chē"],
    "to make a telephone call": ["打电话", "dǎ diàn huà"],
    "big": ["大", "dà"],
    "of": ["的", "de"],
    "point": ["点", "diǎn"],
    "computer": ["电脑", "diàn nǎo"],
    "television": ["电视", "diàn shì"],
    "movie": ["电影", "diàn yǐng"],
    "thing": ["东西", "dōng xi"],
    "all": ["都", "dōu"],
    "to read": ["读", "dú"],
    "unworthy": ["对不起", "duì bu qǐ"],
    "many": ["多", "duō"],
    "how much": ["多少", "duō shao"],
    "son": ["儿子", "ér zi"],
    "two": ["二", "èr"],
    "restaurant": ["饭馆", "fàn guǎn"],
    "airplane": ["飞机", "fēi jī"],
    "minute": ["分钟", "fēn zhōng"],
    "happy": ["高兴", "gāo xìng"],
    "basic measure word": ["个", "gè"],
    "to work": ["工作", "gōng zuò"],
    "dog": ["狗", "gǒu"],
    "Chinese language": ["汉语", "Hàn yǔ"],
    "good": ["好", "hǎo"],
    "to drink": ["喝", "hē"],
    "and": ["和", "hé"],
    "(adverb of degree)": ["很", "hěn"],
    "rear": ["后面", "hòu mian"],
    "to curve": ["回", "huí"],
    "can": ["会", "huì"],
    "train station": ["火车站", "huǒ chē zhàn"],
    "how much (variant)": ["几", "jǐ"],
    "home": ["家", "jiā"],
    "to shout": ["叫", "jiào"],
    "today": ["今天", "jīn tiān"],
    "nine": ["九", "jiǔ"],
    "to open": ["开", "kāi"],
    "to see": ["看", "kàn"],
    "to see (variant)": ["看见", "kàn jiàn"],
    "lump (of earth)": ["块", "kuài"],
    "to come": ["来", "lái"],
    "teacher": ["老师", "lǎo shī"],
    "(modal particle intensifying preceding clause)": ["了", "le"],
    "cold": ["冷", "lěng"],
    "li (Chinese mile)": ["里", "lǐ"],
    "zero": ["零", "líng"],
    "six": ["六", "liù"],
    "mama": ["妈妈", "mā ma"],
    "(question tag)": ["吗", "ma"],
    "to buy": ["买", "mǎi"],
    "cat": ["猫", "māo"],
    "(negative prefix for verbs)": ["没", "méi"],
    "it doesn't matter": ["没关系", "méi guān xi"],
    "(cooked) rice": ["米饭", "mǐ fàn"],
    "tomorrow": ["明天", "míng tiān"],
    "name (of a person or thing)": ["名字", "míng zi"],
    "how": ["哪", "nǎ"],
    "that": ["那", "nà"],
    "particle indicating that a previously asked question is to be applied to the preceding word": ["呢", "ne"],
    "to be able to": ["能", "néng"],
    "you (informal": ["你", "nǐ"],
    "year": ["年", "nián"],
    "daughter": ["女儿", "nǚ ér"],
    "friend": ["朋友", "péng you"],
    "pretty": ["漂亮", "piào liang"],
    "apple": ["苹果", "píng guǒ"],
    "seven": ["七", "qī"],
    "coin": ["钱", "qián"],
    "ahead": ["前面", "qián miàn"],
    "to ask": ["请", "qǐng"],
    "to go": ["去", "qù"],
    "to warm up": ["热", "rè"],
    "man": ["人", "rén"],
    "to know": ["认识", "rèn shi"],
    "sun": ["日", "rì"],
    "three": ["三", "sān"],
    "store": ["商店", "shāng diàn"],
    "on top": ["上", "shàng"],
    "morning": ["上午", "shàng wǔ"],
    "few": ["少", "shǎo"],
    "who": ["谁", "shéi"],
    "what?": ["什么", "shén me"],
    "ten": ["十", "shí"],
    "time": ["时候", "shí hou"],
    "is": ["是", "shì"],
    "book": ["书", "shū"],
    "water": ["水", "shuǐ"],
    "fruit": ["水果", "shuǐ guǒ"],
    "to go to bed": ["睡觉", "shuì jiào"],
    "to speak": ["说话", "shuō huà"],
    "four": ["四", "sì"],
    "classifier for years (of age)": ["岁", "suì"],
    "he or him": ["他", "tā"],
    "she": ["她", "tā"],
    "highest": ["太", "tài"],
    "weather": ["天气", "tiān qì"],
    "to listen": ["听", "tīng"],
    "to study at the same school": ["同学", "tóng xué"],
    "to feed": ["喂", "wèi"],
    "I": ["我", "wǒ"],
    "we": ["我们", "wǒ men"],
    "five": ["五", "wǔ"],
    "to like": ["喜欢", "xǐ huan"],
    "down": ["下", "xià"],
    "afternoon": ["下午", "xià wǔ"],
    "to rain": ["下雨", "xià yǔ"],
    "teacher (variant)": ["先生", "xiān sheng"],
    "now": ["现在", "xiàn zài"],
    "to think": ["想", "xiǎng"],
    "small": ["小", "xiǎo"],
    "young lady": ["小姐", "xiǎo jie"],
    "some": ["些", "xiē"],
    "to write": ["写", "xiě"],
    "to thank": ["谢谢", "xiè xie"],
    "week": ["星期", "xīng qī"],
    "student": ["学生", "xué sheng"],
    "to learn": ["学习", "xué xí"],
    "school": ["学校", "xué xiào"],
    "one": ["一", "yī"],
    "clothes": ["衣服", "yī fu"],
    "doctor": ["医生", "yī shēng"],
    "hospital": ["医院", "yī yuàn"],
    "chair": ["椅子", "yǐ zi"],
    "to have": ["有", "yǒu"],
    "moon": ["月", "yuè"],
    "(located) at": ["在", "zài"],
    "goodbye": ["再见", "zài jiàn"],
    "how?": ["怎么", "zěn me"],
    "how about": ["怎么样", "zěn me yàng"],
    "this": ["这", "zhè"],
    "China": ["中国", "Zhōng guó"],
    "noon": ["中午", "zhōng wǔ"],
    "to live": ["住", "zhù"],
    "table": ["桌子", "zhuō zi"],
    "letter": ["字", "zì"],
    "yesterday": ["昨天", "zuó tiān"],
    "to sit": ["坐", "zuò"],
    "to do": ["做", "zuò"],
    },
    {
    "modal particle indicating suggestion or surmise": ["吧", "ba"],
    "white": ["白", "bái"],
    "hundred": ["百", "bǎi"],
    "assistance": ["帮助", "bāng zhù"],
    "newspaper": ["报纸", "bào zhǐ"],
    "particle used for comparison": ["比", "bǐ"],
    "don't": ["别", "bié"],
    "length": ["长", "cháng"],
    "to sing a song": ["唱歌", "chàng gē"],
    "to go out": ["出", "chū"],
    "to bore through": ["穿", "chuān"],
    "a boat": ["船", "chuán"],
    "next in sequence": ["次", "cì"],
    "from": ["从", "cóng"],
    "mistake": ["错", "cuò"],
    "play basketball": ["打篮球", "dá lán qiú"],
    "everyone": ["大家", "dà jiā"],
    "but": ["但是", "dàn shì"],
    "to (a place)": ["到", "dào"],
    "structural particle: used after a verb (or adjective as main verb)": ["得", "de"],
    "to have to": ["得", "děi"],
    "younger brother": ["弟弟", "dì di"],
    "first": ["第一", "dì yī"],
    "to understand": ["懂", "dǒng"],
    "room": ["房间", "fáng jiān"],
    "unusual": ["非常", "fēi cháng"],
    "waiter": ["服务员", "fú wù yuán"],
    "high": ["高", "gāo"],
    "to tell": ["告诉", "gào su"],
    "older brother": ["哥哥", "gē ge"],
    "to": ["给", "gěi"],
    "bus": ["公共汽车", "gōng gòng qì chē"],
    "kilogram (kg)": ["公斤", "gōng jīn"],
    "(business) company": ["公司", "gōng sī"],
    "expensive": ["贵", "guì"],
    "still": ["还", "hái"],
    "child": ["孩子", "hái zi"],
    "tasty": ["好吃", "hǎo chī"],
    "ordinal number": ["号", "hào"],
    "black": ["黑", "hēi"],
    "red": ["红", "hóng"],
    "to welcome": ["欢迎", "huān yíng"],
    "to pay back": ["还", "huán"],
    "to reply": ["回答", "huí dá"],
    "airport": ["机场", "jī chǎng"],
    "(chicken) egg": ["鸡蛋", "jī dàn"],
    "item": ["件", "jiàn"],
    "classroom": ["教室", "jiào shì"],
    "older sister": ["姐姐", "jiě jie"],
    "to introduce (sb to sb)": ["介绍", "jiè shào"],
    "to advance": ["进", "jìn"],
    "near": ["近", "jìn"],
    "at once": ["就", "jiù"],
    "to think": ["觉得", "jué de"],
    "coffee": ["咖啡", "kā fēi"],
    "to begin": ["开始", "kāi shǐ"],
    "to take an exam": ["考试", "kǎo shì"],
    "might (happen)": ["可能", "kě néng"],
    "can": ["可以", "kě yǐ"],
    "subject": ["课", "kè"],
    "rapid": ["快", "kuài"],
    "happy": ["快乐", "kuài lè"],
    "tired": ["累", "lèi"],
    "to leave": ["离", "lí"],
    "both": ["两", "liǎng"],
    "road": ["路", "lù"],
    "trip": ["旅游", "lǚ yóu"],
    "to sell": ["卖", "mài"],
    "slow": ["慢", "màn"],
    "busy": ["忙", "máng"],
    "each": ["每", "měi"],
    "younger sister": ["妹妹", "mèi mei"],
    "gate": ["门", "mén"],
    "a man": ["男人", "nán rén"],
    "you (courteous)": ["您", "nín"],
    "cow's milk": ["牛奶", "niú nǎi"],
    "woman": ["女人", "nǚ rén"],
    "lateral": ["旁边", "páng biān"],
    "to walk quickly": ["跑步", "pǎo bù"],
    "small advantages": ["便宜", "pián yi"],
    "ticket": ["票", "piào"],
    "wife": ["妻子", "qī zi"],
    "to get out of bed": ["起床", "qǐ chuáng"],
    "a swing": ["千", "qiān"],
    "clear": ["晴", "qíng"],
    "last year": ["去年", "qù nián"],
    "to yield": ["让", "ràng"],
    "to go to work": ["上班", "shàng bān"],
    "(human) body": ["身体", "shēn tǐ"],
    "to fall ill": ["生病", "shēng bìng"],
    "birthday": ["生日", "shēng rì"],
    "time": ["时间", "shí jiān"],
    "affair": ["事情", "shì qing"],
    "wrist watch": ["手表", "shǒu biǎo"],
    "cell phone": ["手机", "shǒu jī"],
    "to deliver": ["送", "sòng"],
    "therefore": ["所以", "suǒ yǐ"],
    "it": ["它", "tā"],
    "to kick": ["踢", "tī"],
    "topic": ["题", "tí"],
    "to dance": ["跳舞", "tiào wǔ"],
    "outside": ["外", "wài"],
    "to finish": ["完", "wán"],
    "toy": ["玩", "wán"],
    "evening": ["晚上", "wǎn shang"],
    "for": ["为", "wèi"],
    "to ask": ["问", "wèn"],
    "question": ["问题", "wèn tí"],
    "watermelon": ["西瓜", "xī guā"],
    "to wish for": ["希望", "xī wàng"],
    "to wash": ["洗", "xǐ"],
    "towards": ["向", "xiàng"],
    "hour": ["小时", "xiǎo shí"],
    "laugh": ["笑", "xiào"],
    "new": ["新", "xīn"],
    "family name": ["姓", "xìng"],
    "rest": ["休息", "xiū xi"],
    "snow": ["雪", "xuě"],
    "color": ["颜色", "yán sè"],
    "eye": ["眼睛", "yǎn jing"],
    "mutton": ["羊肉", "yáng ròu"],
    "medicine": ["药", "yào"],
    "important": ["要", "yào"],
    "also": ["也", "yě"],
    "already": ["已经", "yǐ jīng"],
    "in the same place": ["一起", "yī qǐ"],
    "idea": ["意思", "yì si"],
    "overcast (weather)": ["阴", "yīn"],
    "because": ["因为", "yīn wèi"],
    "swimming": ["游泳", "yóu yǒng"],
    "right side": ["右边", "yòu bian"],
    "fish": ["鱼", "yú"],
    "Chinese monetary unit": ["元", "yuán"],
    "far": ["远", "yuǎn"],
    "to move": ["运动", "yùn dòng"],
    "again": ["再", "zài"],
    "early morning": ["早上", "zǎo shang"],
    "to open up": ["张", "zhāng"],
    "chief": ["长", "zhǎng"],
    "husband": ["丈夫", "zhàng fu"],
    "to try to find": ["找", "zhǎo"],
    "aspect particle indicating action in progress": ["着", "zhe"],
    "really": ["真", "zhēn"],
    "in the process of (doing something or happening)": ["正在", "zhèng zài"],
    "to know": ["知道", "zhī dào"],
    "preparation": ["准备", "zhǔn bèi"],
    "bicycle": ["自行车", "zì xíng chē"],
    "to walk": ["走", "zǒu"],
    "most": ["最", "zuì"],
    "left": ["左边", "zuǒ bian"],
  },
  {
    "maternal aunt": ["阿姨", "ā yí"],
    "modal particle ending sentence": ["啊", "a"],
    "short": ["矮", "ǎi"],
    "to like": ["爱好", "ài hào"],
    "quiet": ["安静", "ān jìng"],
    "to hold": ["把", "bǎ"],
    "to move": ["搬", "bān"],
    "team": ["班", "bān"],
    "half": ["半", "bàn"],
    "means": ["办法", "bàn fǎ"],
    "office": ["办公室", "bàn gōng shì"],
    "to help": ["帮忙", "bāng máng"],
    "to cover": ["包", "bāo"],
    "to eat till full": ["饱", "bǎo"],
    "north": ["北方", "běi fāng"],
    "quilt": ["被", "bèi"],
    "nose": ["鼻子", "bí zi"],
    "to compare": ["比较", "bǐ jiào"],
    "competition (sports etc)": ["比赛", "bǐ sài"],
    "to have to": ["必须", "bì xū"],
    "change": ["变化", "biàn huà"],
    "to express": ["表示", "biǎo shì"],
    "play": ["表演", "biǎo yǎn"],
    "other people": ["别人", "bié ren"],
    "guesthouse": ["宾馆", "bīn guǎn"],
    "icebox": ["冰箱", "bīng xiāng"],
    "a moment ago": ["才", "cái"],
    "menu": ["菜单", "cài dān"],
    "to participate": ["参加", "cān jiā"],
    "grass": ["草", "cǎo"],
    "layer": ["层", "céng"],
    "to differ from": ["差", "chà"],
    "supermarket (abbr.)": ["超市", "chāo shì"],
    "shirt": ["衬衫", "chèn shān"],
    "achievement": ["成绩", "chéng jì"],
    "city": ["城市", "chéng shì"],
    "to arrive late": ["迟到", "chí dào"],
    "to appear": ["出现", "chū xiàn"],
    "besides": ["除了", "chú le"],
    "kitchen": ["厨房", "chú fáng"],
    "spring (time)": ["春", "chūn"],
    "word (general term including monosyllables through to short phrases)": ["词语", "cí yǔ"],
    "acute (of sight and hearing)": ["聪明", "cōng ming"],
    "to clean": ["打扫", "dǎ sǎo"],
    "to plan": ["打算", "dǎ suàn"],
    "band": ["带", "dài"],
    "anxious": ["担心", "dān xīn"],
    "cake": ["蛋糕", "dàn gāo"],
    "only natural": ["当然", "dāng rán"],
    "-ly": ["地", "de"],
    "lamp": ["灯", "dēng"],
    "low": ["低", "dī"],
    "area": ["地方", "dì fang"],
    "subway": ["地铁", "dì tiě"],
    "map": ["地图", "dì tú"],
    "elevator": ["电梯", "diàn tī"],
    "electronic": ["电子", "diàn zǐ"],
    "sound of beating a drum": ["冬", "dōng"],
    "east": ["东", "dōng"],
    "animal": ["动物", "dòng wù"],
    "short or brief": ["短", "duǎn"],
    "paragraph": ["段", "duàn"],
    "to engage in physical exercise": ["锻炼", "duàn liàn"],
    "how (wonderful etc)": ["多么", "duō me"],
    "to be hungry": ["饿", "è"],
    "(not only ...) but also": ["而且", "ér qiě"],
    "ear": ["耳朵", "ěr duo"],
    "to have a high temperature (from illness)": ["发烧", "fā shāo"],
    "to find": ["发现", "fā xiàn"],
    "convenient": ["方便", "fāng biàn"],
    "to release": ["放", "fàng"],
    "to feel relieved": ["放心", "fàng xīn"],
    "to divide": ["分", "fēn"],
    "(in the) vicinity": ["附近", "fù jìn"],
    "review": ["复习", "fù xí"],
    "clean": ["干净", "gān jìng"],
    "to dare": ["敢", "gǎn"],
    "to catch cold": ["感冒", "gǎn mào"],
    "(just) a moment ago": ["刚才", "gāng cái"],
    "according to": ["根据", "gēn jù"],
    "heel": ["跟", "gēn"],
    "more": ["更", "gèng"],
    "public park": ["公园", "gōng yuán"],
    "narrative": ["故事", "gù shi"],
    "to blow (of the wind)": ["刮", "guā"],
    "mountain pass": ["关", "guān"],
    "relation": ["关系", "guān xì"],
    "to care for sth": ["关心", "guān xīn"],
    "pertaining to": ["关于", "guān yú"],
    "country": ["国家", "guó jiā"],
    "fruit juice": ["果汁", "guǒ zhī"],
    "(in the) past": ["过去", "guò qu"],
    "or/still": ["还是", "hái shi"],
    "to be afraid": ["害怕", "hài pà"],
    "river": ["河", "hé"],
    "blackboard": ["黑板", "hēi bǎn"],
    "passport": ["护照", "hù zhào"],
    "flower": ["花", "huā"],
    "garden": ["花园", "huā yuán"],
    "to draw": ["画", "huà"],
    "bad": ["坏", "huài"],
    "environment": ["环境", "huán jìng"],
    "to change": ["换", "huàn"],
    "yellow": ["黄", "huáng"],
    "meeting": ["会议", "huì yì"],
    "or": ["或者", "huò zhě"],
    "opportunity": ["机会", "jī huì"],
    "almost": ["几乎", "jī hū"],
    "extremely": ["极", "jí"],
    "to remember": ["记得", "jì de"],
    "time": ["季节", "jì jié"],
    "inspection": ["检查", "jiǎn chá"],
    "simple": ["简单", "jiǎn dān"],
    "to meet": ["见面", "jiàn miàn"],
    "health": ["健康", "jiàn kāng"],
    "to speak": ["讲", "jiǎng"],
    "to teach": ["教", "jiāo"],
    "foot": ["脚", "jiǎo"],
    "angle": ["角", "jiǎo"],
    "to receive": ["接", "jiē"],
    "street": ["街道", "jiē dào"],
    "program": ["节目", "jié mù"],
    "holiday": ["节日", "jié rì"],
    "to marry": ["结婚", "jié hūn"],
    "termination": ["结束", "jié shù"],
    "to settle (a dispute)": ["解决", "jiě jué"],
    "to lend": ["借", "jiè"],
    "day to day": ["经常", "jīng cháng"],
    "to pass": ["经过", "jīng guò"],
    "manager": ["经理", "jīng lǐ"],
    "(long) time": ["久", "jiǔ"],
    "old/used": ["旧", "jiù"],
    "to hold (a meeting)": ["举行", "jǔ xíng"],
    "sentence": ["句子", "jù zi"],
    "to decide (to do something)": ["决定", "jué dìng"],
    "thirsty": ["渴", "kě"],
    "adorable": ["可爱", "kě ài"],
    "quarter (hour)": ["刻", "kè"],
    "visitor": ["客人", "kè rén"],
    "air conditioning": ["空调", "kōng tiáo"],
    "mouth": ["口", "kǒu"],
    "to cry": ["哭", "kū"],
    "trousers": ["裤子", "kù zi"],
    "chopsticks": ["筷子", "kuài zi"],
    "blue": ["蓝", "lán"],
    "old": ["老", "lǎo"],
    "to depart": ["离开", "lí kāi"],
    "gift": ["礼物", "lǐ wù"],
    "history": ["历史", "lì shǐ"],
    "face": ["脸", "liǎn"],
    "exercise": ["练习", "liàn xí"],
    "classifier for vehicles": ["辆", "liàng"],
    "to understand": ["了解", "liǎo jiě"],
    "neighbor": ["邻居", "lín jū"],
    "house with more than 1 story": ["楼", "lóu"],
    "green": ["绿", "lǜ"],
    "horse": ["马", "mǎ"],
    "at once": ["马上", "mǎ shàng"],
    "satisfied": ["满意", "mǎn yì"],
    "hat": ["帽子", "mào zi"],
    "rice": ["米", "mǐ"],
    "bread": ["面包", "miàn bāo"],
    "noodles": ["面条", "miàn tiáo"],
    "understand": ["明白", "míng bai"],
    "to take": ["拿", "ná"],
    "(informal) grandma (paternal grandmother)": ["奶奶", "nǎi nai"],
    "south": ["南", "nán"],
    "difficult (to...)": ["难", "nán"],
    "to feel sad": ["难过", "nán guò"],
    "grade": ["年级", "nián jí"],
    "young": ["年轻", "nián qīng"],
    "bird": ["鸟", "niǎo"],
    "great effort": ["努力", "nǔ lì"],
    "to climb a mountain": ["爬山", "pá shān"],
    "tray": ["盘子", "pán zi"],
    "fat": ["胖", "pàng"],
    "beer": ["啤酒", "pí jiǔ"],
    "grape": ["葡萄", "pú tao"],
    "Mandarin (common language)": ["普通话", "pǔ tōng huà"],
    "to ride (an animal or bike)": ["骑", "qí"],
    "actually": ["其实", "qí shí"],
    "other": ["其他", "qí tā"],
    "strange": ["奇怪", "qí guài"],
    "(lead) pencil": ["铅笔", "qiān bǐ"],
    "clear/understand": ["清楚", "qīng chu"],
    "a swing": ["秋", "qiū"],
    "skirt": ["裙子", "qún zi"],
    "then": ["然后", "rán hòu"],
    "cordial": ["热情", "rè qíng"],
    "to believe": ["认为", "rèn wéi"],
    "conscientious": ["认真", "rèn zhēn"],
    "easy": ["容易", "róng yì"],
    "if": ["如果", "rú guǒ"],
    "umbrella": ["伞", "sǎn"],
    "to be on the internet": ["上网", "shàng wǎng"],
    "angry": ["生气", "shēng qì"],
    "voice": ["声音", "shēng yīn"],
    "to make": ["使", "shǐ"],
    "world": ["世界", "shì jiè"],
    "thin": ["瘦", "shòu"],
    "comfortable": ["舒服", "shū fu"],
    "father's younger brother": ["叔叔", "shū shu"],
    "tree": ["树", "shù"],
    "mathematics": ["数学", "shù xué"],
    "to brush": ["刷", "shuā"],
    "two": ["双", "shuāng"],
    "level (of achievement etc)": ["水平", "shuǐ píng"],
    "chauffeur": ["司机", "sī jī"],
    "although": ["虽然", "suī rán"],
    "sun": ["太阳", "tài yáng"],
    "sugar": ["糖", "táng"],
    "especially": ["特别", "tè bié"],
    "(it) hurts": ["疼", "téng"],
    "to raise": ["提高", "tí gāo"],
    "sports": ["体育", "tǐ yù"],
    "sweet": ["甜", "tián"],
    "strip": ["条", "tiáo"],
    "colleague": ["同事", "tóng shì"],
    "to agree": ["同意", "tóng yì"],
    "hair (on the head)": ["头发", "tóu fa"],
    "sudden": ["突然", "tū rán"],
    "library": ["图书馆", "tú shū guǎn"],
    "leg": ["腿", "tuǐ"],
    "to complete": ["完成", "wán chéng"],
    "bowl": ["碗", "wǎn"],
    "ten thousand": ["万", "wàn"],
    "to forget": ["忘记", "wàng jì"],
    "in order to": ["为了", "wèi le"],
    "why?": ["为什么", "wèi shén me"],
    "position": ["位", "wèi"],
    "culture": ["文化", "wén huà"],
    "west": ["西", "xī"],
    "habit": ["习惯", "xí guàn"],
    "toilet": ["洗手间", "xǐ shǒu jiān"],
    "to bathe": ["洗澡", "xǐ zǎo"],
    "summer": ["夏", "xià"],
    "early": ["先", "xiān"],
    "banana": ["香蕉", "xiāng jiāo"],
    "identical": ["相同", "xiāng tóng"],
    "to be convinced (that sth is true)": ["相信", "xiāng xìn"],
    "to resemble": ["像", "xiàng"],
    "to be careful": ["小心", "xiǎo xīn"],
    "(college": ["校长", "xiào zhǎng"],
    "shoe": ["鞋", "xié"],
    "news": ["新闻", "xīn wén"],
    "fresh (experience": ["新鲜", "xīn xiān"],
    "letter": ["信", "xìn"],
    "suitcase": ["行李箱", "xíng li xiāng"],
    "interest (desire to know about sth)": ["兴趣", "xìng qù"],
    "panda": ["熊猫", "xióng māo"],
    "to need": ["需要", "xū yào"],
    "to select": ["选择", "xuǎn zé"],
    "spectacles": ["眼镜", "yǎn jìng"],
    "to request": ["要求", "yāo qiú"],
    "(informal) father's father": ["爷爷", "yé ye"],
    "surely": ["一定", "yī dìng"],
    "altogether": ["一共", "yī gòng"],
    "a while": ["一会儿", "yī huì r"],
    "same": ["一样", "yī yàng"],
    "after": ["以后", "yǐ hòu"],
    "before": ["以前", "yǐ qián"],
    "to think": ["以为", "yǐ wéi"],
    "just like": ["一般", "yī bān"],
    "one side": ["一边", "yī biān"],
    "straight (in a straight line)": ["一直", "yī zhí"],
    "music": ["音乐", "yīn yuè"],
    "bank": ["银行", "yín háng"],
    "ought to": ["应该", "yīng gāi"],
    "an influence": ["影响", "yǐng xiǎng"],
    "to use": ["用", "yòng"],
    "game": ["游戏", "yóu xì"],
    "famous": ["有名", "yǒu míng"],
    "(once) again": ["又", "yòu"],
    "to meet (variant)": ["遇到", "yù dào"],
    "willing": ["愿意", "yuàn yì"],
    "to exceed": ["越", "yuè"],
    "moon": ["月亮", "yuè liang"],
    "cloud": ["云", "yún"],
    "station": ["站", "zhàn"],
    "to worry": ["着急", "zháo jí"],
    "to take care of": ["照顾", "zhào gu"],
    "photograph": ["照片", "zhào piàn"],
    "camera": ["照相机", "zhào xiàng jī"],
    "classifier for birds and certain animals": ["只", "zhī"],
    "but": ["只", "zhǐ"],
    "at last": ["终于", "zhōng yú"],
    "between": ["中间", "zhōng jiān"],
    "type of": ["种", "zhǒng"],
    "important": ["重要", "zhòng yào"],
    "weekend": ["周末", "zhōu mò"],
    "main": ["主要", "zhǔ yào"],
    "to wish": ["祝", "zhù"],
    "to take note of": ["注意", "zhù yì"],
    "dictionary": ["字典", "zì diǎn"],
    "oneself": ["自己", "zì jǐ"],
    "always": ["总是", "zǒng shì"],
    "recent": ["最近", "zuì jìn"],
    "school assignment": ["作业", "zuò yè"],
    "to act on": ["作用", "zuò yòng"],
  }];
  const dataKeys = Object.keys(data[0]).concat(Object.keys(data[1])).concat(Object.keys(data[2]));

  const updateCardInfo = () => {
    let idx = 2;

    if (index < 150) idx = 0;
    else if (index < 300) idx = 1;
    setLevel(idx);
    setSide(0);
    setCurrent([dataKeys[index], data[idx][dataKeys[index]]]);
  };

  const goToNext = () => {
    if (index < dataKeys.length-1) {
      setIndex(index+1);
      console.log("index increased");
    } else {
      setIndex(0);
    }
    updateCardInfo();
  };

  const goToPrev = () => {
    if (index > 0) {
      setIndex(index-1);
    } else {
      setIndex(dataKeys.length-1);
    }
    updateCardInfo();
  };

  const flipCard = () => {
    if (currentSide == 0) setSide(1);
    else setSide(0);
  }

  return (
    <>
      <h1>Learn Chinese</h1>
      <h3><strong>学中文</strong> (xué zhōngwén)</h3>
      <p>Study beginner and intermediate Chinese vocabulary!</p>
      {/* <p>{dataKeys}</p> */}
      <div className="flashcard" onClick={flipCard}>
        <div className={`flashcard-inner ${currentSide == 1 ? 'flipped' : ''}`}>
          <div className={`flashcard-front`}>
            <p><strong>{currentCard[0]}</strong></p>
            <p>HSK {currentLevel + 1}</p>
          </div>
          <div className={`flashcard-back`}>
            <p><strong>{currentCard[1][0]}</strong> ({currentCard[1][1]})</p>
          </div>
        </div>
      </div>

      <button onClick={goToPrev}>⬅️</button>
      <button onClick={goToNext}>➡️</button>

      <p>Number of cards: {dataKeys.length}</p>
    </>
  )
}

export default App
